Uniform iframes for embedding video/youtube links.
RetroPie/RetroPie-Docs pull request #123
Opened 2023-01-17 19:01 UTC by Gemba

Looks massive but in essence it is the uniform usage of `<iframe ...>` for yt links, using the `youtube-nocookie` site.

I left  the `Bluetooth-Controller.md` page as-is regarding any youtube links as  it needs an overhaul in general.

Some minor issues also addressed:
-  Removal of trailing spaces
-  Some tables fixed in layout

2023-01-18 05:32 UTC, cmitu requested changes
Thank you for the changes. Included are more than what's advertised, but they're mostly good changed.

I have a couple of observations:

* Whitespaces matter at the end of the line - 4 whitespaces will force line break without starting a new paragraph. I added a few of those throughout the docs and I'd like to keep them and so I marked the places where they should be reverted. 

* The video `iframe` should have the `allow` attribute with at least `fullscreen` available, otherwise you can't make the embedded video fullscreen. I see you replaced some of the existing `iframe` video tags and stripped the `allow` tag - please restore it and add it also to the other added `iframes`.

2023-01-18 05:32 UTC, cmitu commented on docs/RetroArch-Configuration.md
> -In the terminal, type and enter
Don't delete the whitespaces here.

2023-01-18 05:32 UTC, cmitu commented on docs/Sega-CD.md
> -Accepted File Extensions: **.bin .chd .cue .iso**, **.m3u** for multi-disc games.
Don't delete the whitespaces here.

2023-01-18 18:14 UTC, Gemba commented
Ah, thanks for pointing out. Reverted the 4 spaces and had a close look at the changes again.
The iframes do contain all previous attributes again.

2023-01-18 18:14 UTC, Gemba commented on docs/Sega-CD.md
> -Accepted File Extensions: **.bin .chd .cue .iso**, **.m3u** for multi-disc games.
Thanks. Done.

2023-01-19 17:25 UTC, cmitu approved these changes
Looks good !
Thank you for the additions and changes.

2023-01-19 17:25 UTC, merged